services:
  - type: web
    name: telegram-gpt-bot
    env: python
    region: oregon
    plan: free
    rootDir: .                # 如果你的代码在子目录，改成子目录路径
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
