services:
  - type: web
    name: telegram-checkin-bot-pro
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BASE_URL
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
